### ISSUE TITLE
Overlapping HTML tags

### ISSUE THREAD

**Issue by zachfedor** [Lazaro300x/more-css-practice#2]
https://github.com/Lazaro300x/more-css-practice/blob/b5fa37240f644be1a3b40652d22875a90a327ca3/airbnb/index.html#L18-L30

You open your `<article>` first, then your `<form>`. But you attempt to close the article before your form. If your form is nested within the article, then you have to close it first:
```html
<article>
   <form>
      ...
   </form>
</article>
```

**Comment by zachfedor** [comment]
Also, you need to close your `<footer>` element in this same file.

**Comment by Lazaro300x** [comment]
All set!
